services:
  playwright:
    build: .
    env_file:
      - .env
    environment:
      PLAYWRIGHT_BASE_URL: ${PLAYWRIGHT_BASE_URL:-http://localhost:3000}
    volumes:
      - ./tests:/app/tests
      - ./playwright-report:/app/playwright-report
    command: >-
      bash -lc "npx playwright test --reporter=html,list"

volumes: {}
